export const SET_GAME_STARTED = 'SET_GAME_STARTED', SET_INSTRUCTIONS_EXPANDED = 'SET_INSTRUCTIONS_EXPANDED', SET_GUESS = 'SET_GUESS';

export const DECK = {
    FETCH_SUCCESS: 'DECK_FETCH_SUCCESS',
    FETCH_ERROR: 'DECK_FETCH_ERROR'
};

export const CARD = {
    FETCH_SUCCESS: 'CARD_FETCH_SUCCESS',
    FETCH_ERROR: 'CARD_FETCH_ERROR'
};
